version: "3.9"

services:
  database:
    image: postgres:15-bullseye
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: MyPassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  database-backup:
    build:
      context: .
      dockerfile: ./etc/backups/Dockerfile
    container_name: database-backup
    restart: always
    volumes:
      - ./backups:/backups
    depends_on:
      - database
    
volumes:
  postgres-data:
