#!/bin/bash

# Variables
USER=postgres
PASSWORD=MyPassword
HOST=database
PORT=5432
DB=alesquare
BACKUP_DIR=/backups
BACKUP_FILE=$BACKUP_DIR/mydb_$(date +\%Y-\%m-\%d_\%H-\%M-\%S).sql

# Create backup directory if it doesn't exist
mkdir -p $BACKUP_DIR

# Backup database
PGPASSWORD=$PASSWORD pg_dump -h $HOST -p $PORT -U $USER -d $DB -F p > $BACKUP_FILE
